# Generated by Django 5.1.6 on 2025-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Science', 'Science'), ('General', 'General')], max_length=50)),
                ('sentiment', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Neutral', max_length=20)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
